// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author               string   `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{0}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Book) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

type BookListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookListRequest) Reset()         { *m = BookListRequest{} }
func (m *BookListRequest) String() string { return proto.CompactTextString(m) }
func (*BookListRequest) ProtoMessage()    {}
func (*BookListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{1}
}

func (m *BookListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookListRequest.Unmarshal(m, b)
}
func (m *BookListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookListRequest.Marshal(b, m, deterministic)
}
func (m *BookListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookListRequest.Merge(m, src)
}
func (m *BookListRequest) XXX_Size() int {
	return xxx_messageInfo_BookListRequest.Size(m)
}
func (m *BookListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookListRequest proto.InternalMessageInfo

type BookListResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookListResponse) Reset()         { *m = BookListResponse{} }
func (m *BookListResponse) String() string { return proto.CompactTextString(m) }
func (*BookListResponse) ProtoMessage()    {}
func (*BookListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{2}
}

func (m *BookListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookListResponse.Unmarshal(m, b)
}
func (m *BookListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookListResponse.Marshal(b, m, deterministic)
}
func (m *BookListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookListResponse.Merge(m, src)
}
func (m *BookListResponse) XXX_Size() int {
	return xxx_messageInfo_BookListResponse.Size(m)
}
func (m *BookListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookListResponse proto.InternalMessageInfo

func (m *BookListResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type BookCreateRequest struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCreateRequest) Reset()         { *m = BookCreateRequest{} }
func (m *BookCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BookCreateRequest) ProtoMessage()    {}
func (*BookCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{3}
}

func (m *BookCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCreateRequest.Unmarshal(m, b)
}
func (m *BookCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCreateRequest.Marshal(b, m, deterministic)
}
func (m *BookCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCreateRequest.Merge(m, src)
}
func (m *BookCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BookCreateRequest.Size(m)
}
func (m *BookCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookCreateRequest proto.InternalMessageInfo

func (m *BookCreateRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type BookCreateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookCreateResponse) Reset()         { *m = BookCreateResponse{} }
func (m *BookCreateResponse) String() string { return proto.CompactTextString(m) }
func (*BookCreateResponse) ProtoMessage()    {}
func (*BookCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{4}
}

func (m *BookCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookCreateResponse.Unmarshal(m, b)
}
func (m *BookCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookCreateResponse.Marshal(b, m, deterministic)
}
func (m *BookCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookCreateResponse.Merge(m, src)
}
func (m *BookCreateResponse) XXX_Size() int {
	return xxx_messageInfo_BookCreateResponse.Size(m)
}
func (m *BookCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookCreateResponse proto.InternalMessageInfo

type BookGetRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookGetRequest) Reset()         { *m = BookGetRequest{} }
func (m *BookGetRequest) String() string { return proto.CompactTextString(m) }
func (*BookGetRequest) ProtoMessage()    {}
func (*BookGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{5}
}

func (m *BookGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookGetRequest.Unmarshal(m, b)
}
func (m *BookGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookGetRequest.Marshal(b, m, deterministic)
}
func (m *BookGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookGetRequest.Merge(m, src)
}
func (m *BookGetRequest) XXX_Size() int {
	return xxx_messageInfo_BookGetRequest.Size(m)
}
func (m *BookGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookGetRequest proto.InternalMessageInfo

func (m *BookGetRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BookGetResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookGetResponse) Reset()         { *m = BookGetResponse{} }
func (m *BookGetResponse) String() string { return proto.CompactTextString(m) }
func (*BookGetResponse) ProtoMessage()    {}
func (*BookGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{6}
}

func (m *BookGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookGetResponse.Unmarshal(m, b)
}
func (m *BookGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookGetResponse.Marshal(b, m, deterministic)
}
func (m *BookGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookGetResponse.Merge(m, src)
}
func (m *BookGetResponse) XXX_Size() int {
	return xxx_messageInfo_BookGetResponse.Size(m)
}
func (m *BookGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookGetResponse proto.InternalMessageInfo

func (m *BookGetResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type BookUpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Book                 *Book    `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookUpdateRequest) Reset()         { *m = BookUpdateRequest{} }
func (m *BookUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*BookUpdateRequest) ProtoMessage()    {}
func (*BookUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{7}
}

func (m *BookUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookUpdateRequest.Unmarshal(m, b)
}
func (m *BookUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookUpdateRequest.Marshal(b, m, deterministic)
}
func (m *BookUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookUpdateRequest.Merge(m, src)
}
func (m *BookUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_BookUpdateRequest.Size(m)
}
func (m *BookUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookUpdateRequest proto.InternalMessageInfo

func (m *BookUpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookUpdateRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type BookUpdateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookUpdateResponse) Reset()         { *m = BookUpdateResponse{} }
func (m *BookUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*BookUpdateResponse) ProtoMessage()    {}
func (*BookUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{8}
}

func (m *BookUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookUpdateResponse.Unmarshal(m, b)
}
func (m *BookUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookUpdateResponse.Marshal(b, m, deterministic)
}
func (m *BookUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookUpdateResponse.Merge(m, src)
}
func (m *BookUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_BookUpdateResponse.Size(m)
}
func (m *BookUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookUpdateResponse proto.InternalMessageInfo

type BookDeleteRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookDeleteRequest) Reset()         { *m = BookDeleteRequest{} }
func (m *BookDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*BookDeleteRequest) ProtoMessage()    {}
func (*BookDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{9}
}

func (m *BookDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookDeleteRequest.Unmarshal(m, b)
}
func (m *BookDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookDeleteRequest.Marshal(b, m, deterministic)
}
func (m *BookDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookDeleteRequest.Merge(m, src)
}
func (m *BookDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_BookDeleteRequest.Size(m)
}
func (m *BookDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookDeleteRequest proto.InternalMessageInfo

func (m *BookDeleteRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BookDeleteResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookDeleteResponse) Reset()         { *m = BookDeleteResponse{} }
func (m *BookDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*BookDeleteResponse) ProtoMessage()    {}
func (*BookDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1c5fb4d8cc22d66a, []int{10}
}

func (m *BookDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookDeleteResponse.Unmarshal(m, b)
}
func (m *BookDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookDeleteResponse.Marshal(b, m, deterministic)
}
func (m *BookDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookDeleteResponse.Merge(m, src)
}
func (m *BookDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_BookDeleteResponse.Size(m)
}
func (m *BookDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookDeleteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Book)(nil), "protobuf.Book")
	proto.RegisterType((*BookListRequest)(nil), "protobuf.BookListRequest")
	proto.RegisterType((*BookListResponse)(nil), "protobuf.BookListResponse")
	proto.RegisterType((*BookCreateRequest)(nil), "protobuf.BookCreateRequest")
	proto.RegisterType((*BookCreateResponse)(nil), "protobuf.BookCreateResponse")
	proto.RegisterType((*BookGetRequest)(nil), "protobuf.BookGetRequest")
	proto.RegisterType((*BookGetResponse)(nil), "protobuf.BookGetResponse")
	proto.RegisterType((*BookUpdateRequest)(nil), "protobuf.BookUpdateRequest")
	proto.RegisterType((*BookUpdateResponse)(nil), "protobuf.BookUpdateResponse")
	proto.RegisterType((*BookDeleteRequest)(nil), "protobuf.BookDeleteRequest")
	proto.RegisterType((*BookDeleteResponse)(nil), "protobuf.BookDeleteResponse")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor_1c5fb4d8cc22d66a) }

var fileDescriptor_1c5fb4d8cc22d66a = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4d, 0x4b, 0xfb, 0x40,
	0x10, 0xc6, 0x49, 0xd2, 0x96, 0xff, 0x7f, 0x2a, 0xd5, 0x2e, 0x45, 0xd2, 0xe8, 0x21, 0xac, 0x1e,
	0x7a, 0xea, 0xa1, 0x22, 0x8a, 0xe0, 0xc5, 0x16, 0x7a, 0xf1, 0x14, 0xf1, 0x03, 0xf4, 0x65, 0xa4,
	0xa1, 0xd5, 0x8d, 0xd9, 0x8d, 0x5f, 0xd5, 0xaf, 0x23, 0xfb, 0x46, 0xb2, 0x6b, 0x44, 0x4f, 0x61,
	0xe7, 0x99, 0x79, 0xe6, 0x97, 0x67, 0xe0, 0x88, 0x6f, 0x76, 0xf8, 0xba, 0x9a, 0x16, 0x25, 0x13,
	0x8c, 0xfc, 0x53, 0x9f, 0x75, 0xf5, 0x42, 0x17, 0xd0, 0x79, 0x60, 0x6c, 0x4f, 0x06, 0x10, 0xe6,
	0xdb, 0x38, 0x48, 0x83, 0x49, 0x94, 0x85, 0xf9, 0x96, 0x8c, 0xa0, 0x2b, 0x72, 0x71, 0xc0, 0x38,
	0x4c, 0x83, 0xc9, 0xff, 0x4c, 0x3f, 0xc8, 0x29, 0xf4, 0x56, 0x95, 0xd8, 0xb1, 0x32, 0x8e, 0x54,
	0xd9, 0xbc, 0xe8, 0x10, 0x8e, 0xa5, 0xcb, 0x63, 0xce, 0x45, 0x86, 0xef, 0x15, 0x72, 0x41, 0x6f,
	0xe1, 0xa4, 0x2e, 0xf1, 0x82, 0xbd, 0x71, 0x24, 0x97, 0xd0, 0x5d, 0x33, 0xb6, 0xe7, 0x71, 0x90,
	0x46, 0x93, 0xfe, 0x6c, 0x30, 0xb5, 0x18, 0x53, 0xd9, 0x9a, 0x69, 0x91, 0xde, 0xc0, 0x50, 0x3e,
	0xe7, 0x25, 0xae, 0x04, 0x1a, 0x3b, 0x42, 0xa1, 0x23, 0x55, 0x45, 0xf8, 0x7d, 0x52, 0x69, 0x74,
	0x04, 0xa4, 0x39, 0xa8, 0x97, 0xd2, 0x14, 0x06, 0xb2, 0xba, 0x44, 0x8b, 0xe6, 0xff, 0x2b, 0xbd,
	0xd6, 0xf4, 0xaa, 0xc3, 0x90, 0xfe, 0x65, 0xdd, 0x52, 0x73, 0x3e, 0x17, 0xdb, 0x06, 0xa7, 0x9f,
	0xa3, 0x35, 0x0a, 0x7f, 0xe7, 0xb6, 0x46, 0x86, 0xfb, 0x42, 0xdb, 0x2f, 0xf0, 0x80, 0x3f, 0xda,
	0xdb, 0x51, 0xdb, 0xa4, 0x47, 0x67, 0x9f, 0x21, 0xf4, 0x65, 0xf9, 0x09, 0xcb, 0x8f, 0x7c, 0x83,
	0xe4, 0x1e, 0x3a, 0xf2, 0x0e, 0x64, 0xec, 0xae, 0x6f, 0x9c, 0x2b, 0x49, 0xda, 0x24, 0x13, 0xc6,
	0x1c, 0x7a, 0x3a, 0x53, 0x72, 0xe6, 0x76, 0x39, 0x27, 0x4a, 0xce, 0xdb, 0x45, 0x63, 0x72, 0x07,
	0xd1, 0x12, 0x05, 0x89, 0xdd, 0xa6, 0xfa, 0x2a, 0xc9, 0xb8, 0x45, 0xa9, 0x01, 0x74, 0x38, 0x3e,
	0x80, 0x93, 0xbd, 0x0f, 0xe0, 0xe6, 0x29, 0x4d, 0x74, 0x4c, 0xbe, 0x89, 0x93, 0xb0, 0x6f, 0xe2,
	0x26, 0xbb, 0xee, 0x29, 0xf1, 0xea, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x67, 0x96, 0xc8, 0xfc, 0x4f,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	List(ctx context.Context, in *BookListRequest, opts ...grpc.CallOption) (*BookListResponse, error)
	Create(ctx context.Context, in *BookCreateRequest, opts ...grpc.CallOption) (*BookCreateResponse, error)
	Get(ctx context.Context, in *BookGetRequest, opts ...grpc.CallOption) (*BookGetResponse, error)
	Update(ctx context.Context, in *BookUpdateRequest, opts ...grpc.CallOption) (*BookUpdateResponse, error)
	Delete(ctx context.Context, in *BookDeleteRequest, opts ...grpc.CallOption) (*BookDeleteResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) List(ctx context.Context, in *BookListRequest, opts ...grpc.CallOption) (*BookListResponse, error) {
	out := new(BookListResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BookService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Create(ctx context.Context, in *BookCreateRequest, opts ...grpc.CallOption) (*BookCreateResponse, error) {
	out := new(BookCreateResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BookService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Get(ctx context.Context, in *BookGetRequest, opts ...grpc.CallOption) (*BookGetResponse, error) {
	out := new(BookGetResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BookService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Update(ctx context.Context, in *BookUpdateRequest, opts ...grpc.CallOption) (*BookUpdateResponse, error) {
	out := new(BookUpdateResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BookService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) Delete(ctx context.Context, in *BookDeleteRequest, opts ...grpc.CallOption) (*BookDeleteResponse, error) {
	out := new(BookDeleteResponse)
	err := c.cc.Invoke(ctx, "/protobuf.BookService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	List(context.Context, *BookListRequest) (*BookListResponse, error)
	Create(context.Context, *BookCreateRequest) (*BookCreateResponse, error)
	Get(context.Context, *BookGetRequest) (*BookGetResponse, error)
	Update(context.Context, *BookUpdateRequest) (*BookUpdateResponse, error)
	Delete(context.Context, *BookDeleteRequest) (*BookDeleteResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) List(ctx context.Context, req *BookListRequest) (*BookListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedBookServiceServer) Create(ctx context.Context, req *BookCreateRequest) (*BookCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedBookServiceServer) Get(ctx context.Context, req *BookGetRequest) (*BookGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedBookServiceServer) Update(ctx context.Context, req *BookUpdateRequest) (*BookUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedBookServiceServer) Delete(ctx context.Context, req *BookDeleteRequest) (*BookDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BookService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).List(ctx, req.(*BookListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BookService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Create(ctx, req.(*BookCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BookService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Get(ctx, req.(*BookGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BookService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Update(ctx, req.(*BookUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.BookService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).Delete(ctx, req.(*BookDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _BookService_List_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _BookService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BookService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BookService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BookService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schema.proto",
}
